name: AWS Lambda CI-CD Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  aws_cdk:
    permissions:
        id-token: write
        contents: read
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            python-version: ["3.11"]
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::882475027024:role/github-actions
            aws-region: us-east-1